### PR TITLE
Text and code revision of P1C1_Sequence1.ipynb & P1C1_Sequence2.ipynb

### PR DESCRIPTION
**Pull request by pitmonticone**
Just fixed a few more typos in `P1C1_Sequence1.ipynb` and reviewed `P1C1_Sequence2.ipynb`.

### CODE REVIEW

**Review by dcownden — APPROVED** [review]

**Comment by dcownden** [comment]
As before, thank you these all look good. Can you point your pull request at this branch, https://github.com/dcownden/PerennialProblemsOfLifeWithABrain/tree/integrate-feedback, instead of main. Still working on the documentation on how best integrate pull requests.

**Comment by pitmonticone** [comment]
Oh sorry, sure. I'll do it in a few hours.

**Comment by pitmonticone** [comment]
Ok @dcownden, done. I thought I couldn’t do it from mobile but it all worked fine.

**Comment by dcownden** [comment]
Great thanks, looks like those are live now.

**Pull request merged**
