### PR TITLE
Text and code revision of P1C1_Sequence1.ipynb

### PR DESCRIPTION
**Pull request by pitmonticone**

### CODE REVIEW

**Review by dcownden — APPROVED** [review]

**Comment by dcownden** [comment]
Thanks for the PR. Typo fixes look good but the CI process seems to not like something about this, possibly committing straight to main. I created a branch https://github.com/dcownden/PerennialProblemsOfLifeWithABrain/tree/text-and-code-revisions-P1C1_sequence1/sequences. Maybe the ci process will be happier if you try to merge into that branch first.

**Comment by pitmonticone** [comment]
Ok, I've just opened a new PR as suggested #16.

**Comment by dcownden** [comment]
Thanks again for those typo fixes, and for your patience. That seems to have worked and your changes look like they are live. We'll need to think through our workflow for incoming PR's and set up some instructions.

**Comment by pitmonticone** [comment]
You're welcome. Thank you for such a great initiative and for your effort! 

Glad to help with the next notebooks, of course.

**Comment by pitmonticone** [comment]
*PS:* @dcownden Do you believe it might be a good idea to activate discussions for this repo in order to efficiently communicate in a PR-independent way? Do you prefer other means such as Slack, Zulip, Mail, Twitter or something else?

**Pull request merged**
