### PR TITLE
Clean text, docstrings and code

### PR DESCRIPTION
**Pull request by pitmonticone**

### CODE REVIEW

**Comment by dcownden** [comment]
Thanks, changes look good but can they be applied against the base version of the notebook at sequences/P1C1_BehaviourAsPolicy/P1C1_Sequence3.ipynb. Tthe sequences/P1C1_BehaviourAsPolicy/student/P1C1_Sequence3.ipynb version of the book is generated by our ci scripts from that base notebook.

**Comment by pitmonticone** [comment]
Sure @dcownden, I’ll fix it tomorrow.

**Comment by pitmonticone** [comment]
@dcownden Done.

**Comment by dcownden** [comment]
That's better, thanks. One more issues though, can you make the pull request to the integrate-feeback branch, or create your own new branch? our CI tools don't like PR's from forked main to original main.

**Comment by pitmonticone** [comment]
Sure @dcownden, I'll do it in a few hours.

**Pull request merged**
